version: "3"
services:
    database:
        container_name: database
        image: postgis/postgis:15-3.3-alpine
        volumes:
            - ./volumes/db:/var/lib/postgresql/data
        restart: unless-stopped

        environment:
            - POSTGRES_DB=directus
            - POSTGRES_USER=directus
            - POSTGRES_PASSWORD=directus
        ports:
            - 5432:5432

        networks:
            - directus-network

    pgadmin:
        image: dpage/pgadmin4:latest
        volumes:
            - ./volumes/pgadmin:/var/lib/pgadmin
        environment:
            - PGADMIN_DEFAULT_PASSWORD=directus
            - PGADMIN_DEFAULT_EMAIL=dev@devix.co
        restart: unless-stopped
        depends_on:
            - database
        ports:
            - 16543:80
        networks:
            - directus-network

    redis:
        container_name: redis
        image: redis:7.0.5-alpine
        environment:
            - REDIS_PASSWORD:password123
        ports:
            - 6379:6379
        restart: unless-stopped
        networks:
            - directus-network

    directus:
        container_name: directus
        restart: unless-stopped
        build: .
        env_file: .dev_env
        ports:
            - 8055:8055
        volumes:
            # - ./uploads:/directus/uploads
            - ./volumes/directus/extensions:/directus/extensions
        depends_on:
            - redis
            - database
        command:
            [
                "/bin/sh",
                "-c",
                "npx directus bootstrap && node ./node_modules/nodemon/bin/nodemon.js --exec npx directus start",
            ]

        networks:
            - directus-network

networks:
    directus-network:
        driver: bridge
